"""Eliminar columnas is_banned y is_muted de User

Revision ID: 3f0bd7e195c6
Revises: d6e8a960ee61
Create Date: 2025-05-01 17:38:18.273457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0bd7e195c6'
down_revision = 'd6e8a960ee61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_is_banned')
        batch_op.drop_index('ix_user_is_muted')
        batch_op.drop_column('is_muted')
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('is_muted', sa.BOOLEAN(), nullable=False))
        batch_op.create_index('ix_user_is_muted', ['is_muted'], unique=False)
        batch_op.create_index('ix_user_is_banned', ['is_banned'], unique=False)

    # ### end Alembic commands ###
