"""Migración inicial con todos los modelos (incluye Ban/Mute/Aprobación)

Revision ID: d6e8a960ee61
Revises: 
Create Date: 2025-05-01 16:05:45.997223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision = 'd6e8a960ee61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_writable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_name'), ['name'], unique=True)

    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setting_key'), ['key'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_is_banned', ['is_banned'], unique=False)
        batch_op.create_index('ix_user_is_muted', ['is_muted'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('ban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ban', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ban_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ban_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ban_user_id'), ['user_id'], unique=False)

    op.create_table('channel_join_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_user_channel_join_request')
    )
    with op.batch_alter_table('channel_join_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_join_request_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_join_request_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_join_request_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_join_request_user_id'), ['user_id'], unique=False)

    op.create_table('channel_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'channel_id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=10), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)

    op.create_table('mute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mute_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mute_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mute_user_id'), ['user_id'], unique=False)

    op.create_table('sticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploader_user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sticker_is_approved'), ['is_approved'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sticker_is_approved'))

    op.drop_table('sticker')
    with op.batch_alter_table('mute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mute_user_id'))
        batch_op.drop_index(batch_op.f('ix_mute_expires_at'))
        batch_op.drop_index(batch_op.f('ix_mute_channel_id'))

    op.drop_table('mute')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))

    op.drop_table('message')
    op.drop_table('channel_members')
    with op.batch_alter_table('channel_join_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_join_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_channel_join_request_status'))
        batch_op.drop_index(batch_op.f('ix_channel_join_request_requested_at'))
        batch_op.drop_index(batch_op.f('ix_channel_join_request_channel_id'))

    op.drop_table('channel_join_request')
    with op.batch_alter_table('ban', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ban_user_id'))
        batch_op.drop_index(batch_op.f('ix_ban_expires_at'))
        batch_op.drop_index(batch_op.f('ix_ban_channel_id'))

    op.drop_table('ban')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index('ix_user_is_muted')
        batch_op.drop_index('ix_user_is_banned')

    op.drop_table('user')
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setting_key'))

    op.drop_table('setting')
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_name'))

    op.drop_table('channel')
    # ### end Alembic commands ###
